apiVersion: nais.io/v1alpha1
kind: Application
metadata:
   name: su-person
   namespace: default
   labels:
      team: supstonad
spec:
   image: {{ image }}
   port: 8080
   liveness:
      path: isalive
   readiness:
      path: isready
   ingresses:
      - {{ingress}}
   #image: docker.pkg.github.com/navikt/myrepository/myapplication:417dcaa2c839b9da72e0189e2cfdd4e90e9cc6fd
   #       ^--- interpolated from the $IMAGE environment variable in the workflow
