apiVersion: nais.io/v1alpha1
kind: Application
metadata:
   name: su-person
   namespace: default
   labels:
      team: supstonad
spec:
   image: {{ image }}
   replicas:
      min: 1
   liveness:
      path: isalive
   readiness:
      path: isready
   webproxy: true
   prometheus:
      enabled: true
      path: /metrics
   secureLogs:
      enabled: true
   vault:
      enabled: true
      paths:
         -  mountPath: /var/run/secrets/nais.io/vault
            kvPath: /secret/supstonad/{{ secret_env }}
         -  mountPath: /var/run/secrets/nais.io/vault/su-person
            kvPath: /kv/{{ cluster }}/fss/su-person/default
         -  mountPath: /var/run/secrets/nais.io/srvuser
            kvPath: /serviceuser/data/{{ secret_env }}/srvsupstonad
         -  mountPath: /var/run/secrets/nais.io/azuread
            kvPath: /azuread/data/{{ secret_env }}/creds/su-person
