apiVersion: nais.io/v1alpha1
kind: Application
metadata:
   name: su-person
   namespace: default
   labels:
      team: supstonad
spec:
   image: {{ image }}
   port: 8080
   liveness:
      path: isalive
   readiness:
      path: isready
   ingresses:
      - {{ingress}}
   vault:
      enabled: true
      paths:
         -  mountPath: /var/run/secrets/nais.io/supstonad
            kvPath: /secret/supstonad/{{ secret_env }}
         -  mountPath: /var/run/secrets/nais.io/vault
            kvPath: /kv/{{ cluster }}/fss/su-person/default
