name: Bygg og deploy ved push til master

on:
   # Trigger the workflow on pull request
   pull_request

env:
   IMAGE: docker.pkg.github.com/${{ github.repository }}/su-person:${{ github.sha }}

jobs:

   build:
      name: Build and test pull request
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@v1
         -  uses: actions/cache@v1
            with:
               path: ~/.gradle/caches
               key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
               restore-keys: |
                  ${{ runner.os }}-gradle-
         -  uses: actions/setup-java@v1
            with:
               java-version: '12.x'
         -  name: test and build
            run: ./gradlew test build
